lint: {}
nf_core_version: 4.0.3
repository_type: pipeline
template:
  author: Yasset Perez-Riverol
  description: Quantitative Mass Spectrometry nf-core workflow
  force: false
  is_nfcore: true
  name: quantms
  org: bigbio
  outdir: .
  version: 1.9.0dev
