repository_type: pipeline

nf_core_version: 4.0.3

lint: {}

template:
  org: bigbio
  name: quantms
  description: Quantitative Mass Spectrometry nf-core workflow
  author: Yasset Perez-Riverol
  version: 1.9.0dev
  force: true
  outdir: /home/daichengxin/gitrepo/latest/pr/43/quantms
  is_nfcore: true
