name: msrescore_fine_tuning
description: A module to perform AlphaPeptDeep fine-tuning
keywords:
  - MS2
  - rescoring
  - fine tuning
tools:
  - custom:
      description: |
        A custom module for AlphaPeptDeep fine tuning.
      homepage: https://github.com/bigbio/quantms
      documentation: https://github.com/bigbio/quantms/tree/readthedocs
input:
  - ms2_model_dir:
      type: path
      description: ms2 model dir
      pattern: "*"
  - idxml_file:
      type: file
      description: idXML identification file
      pattern: "*.idXML"
  - mzml:
      type: file
      description: spectrum data file
      pattern: "*.mzML"
  - meta:
      type: map
      description: Groovy Map containing sample information
output:
  - idxml:
      type: file
      description: idXML identification file after MS2 rescoring
      pattern: "*.idXML"
  - version:
      type: file
      description: File containing software version
      pattern: "versions.yml"
authors:
  - "@daichengxin"
