name: onsite
description: PTM site localization using onsite (AScore, PhosphoRS, or LucXor).
keywords:
  - onsite
  - AScore
  - PhosphoRS
  - LucXor
  - modification
  - PTM
tools:
  - onsite:
      description: |
        Mass spectrometry post-translational modification localization tool
      homepage: https://github.com/bigbio/onsite
      documentation: https://github.com/bigbio/onsite
input:
  - meta:
      type: map
      description: Groovy Map containing sample information
  - mzml_file:
      type: file
      description: Input spectrum file.
      pattern: "*.mzML"
  - id_file:
      type: file
      description: Protein/peptide identifications file
      pattern: "*.idXML"
output:
  - meta:
      type: map
      description: Groovy Map containing sample information
  - out_id_ptmscores:
      type: file
      description: Protein/peptide identifications file with scored PTM sites
      pattern: "*.idXML"
  - log:
      type: file
      description: log file
      pattern: "*.log"
  - version:
      type: file
      description: File containing software version
      pattern: "versions.yml"
authors:
  - "@weizhongchun"
