name: DOWNLOAD_MODEL
description: A module to download quantms-rescoring model
keywords:
  - MS2
  - rescoring
  - fine tuning
tools:
  - custom:
      description: |
        A custom module download quantms-rescoring model.
      homepage: https://github.com/bigbio/quantms
      documentation: https://github.com/bigbio/quantms/tree/readthedocs

output:
  - model_weights:
      type: file
      description: Model weights for MS2 rescoring
      pattern: "*"
  - version:
      type: file
      description: File containing software version
      pattern: "versions.yml"
authors:
  - "@daichengxin"
